PUT http://localhost:3001/api/phonebook/1
Content-Type: application/json

{
  "number": "1234"
}

###
PUT http://localhost:3001/api/phonebook/1
Content-Type: application/json

###
PUT http://localhost:3001/api/phonebook/6646ccb662e18a6b28fef544
Content-Type: application/json

{
  "name": "Tom Lee",
  "number": "123456"
}